### ISSUE TITLE
在推块一段时间的过程中，程序会突然crash。

### ISSUE THREAD

**Issue by AlexiaChen** [FissionAndFusion/FnFnCoreWallet#32]
以下是gdb bt的打印的崩溃堆栈,看样子也是CNetChannel::AddNewBlock中写入流的时候，导致SSE2 mencpy的时候内存没对齐什么的,这个问题纯哥跟我反应过。

@sunhantao  @xdwangchn @gc87 

```
Thread 4 "multiverse" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1d90700 (LWP 12709)]
__memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
35	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
#1  0x00007ffff67f3e5b in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff67e4a03 in std::ostream::write(char const*, long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000000000044a503 in walleve::CWalleveStream::Write (this=0x7ffff1d8e490, 
    s=0x0, n=49)
    at /home/mathxh/projects/FnFnCoreWallet/src/../walleve/walleve/stream/stream.h:47
#4  0x000000000044ddf6 in walleve::CWalleveStream::Serialize<unsigned char, std::allocator<unsigned char> > (this=0x7ffff1d8e490, 
    t=std::vector of length 49, capacity 140737018593400 = {...})
    at /home/mathxh/projects/FnFnCoreWallet/src/../walleve/walleve/stream/stream.h:386
#5  0x0000000000450f9d in walleve::CWalleveStream::Serialize<std::vector<unsigned char, std::allocator<unsigned char> >, boost::integral_constant<int, 0> const> (this=0x7ffff1d8e490, 
    t=std::vector of length 49, capacity 140737018593400 = {...}, opt=...)
    at /home/mathxh/projects/FnFnCoreWallet/src/../walleve/walleve/stream/stream.h:60
#6  0x000000000044f6f0 in CTransaction::WalleveSerialize<boost::integral_constant<int, 0> const> (this=0x7fffe400b380, s=..., opt=...)
---Type <return> to continue, or q <return> to quit---
    at /home/mathxh/projects/FnFnCoreWallet/src/../common/transaction.h:170
#7  0x000000000044dba1 in walleve::CWalleveStream::Serialize<CTransaction, boost::integral_constant<int, 0> const> (this=0x7ffff1d8e490, t=..., opt=...)
    at /home/mathxh/projects/FnFnCoreWallet/src/../walleve/walleve/stream/stream.h:106
#8  0x000000000044bf7d in walleve::CWalleveStream::operator<< <CTransaction> (
    this=0x7ffff1d8e490, t=...)
    at /home/mathxh/projects/FnFnCoreWallet/src/../walleve/walleve/stream/stream.h:66
#9  0x000000000044ad65 in CTransaction::GetHash (this=0x7fffe400b380)
    at /home/mathxh/projects/FnFnCoreWallet/src/../common/transaction.h:127
#10 0x000000000048a3a1 in multiverse::CNetChannel::AddNewBlock (this=0xb79ed0, 
    hashFork=..., hash=..., sched=..., 
    setSchedPeer=std::set with 1 elements = {...}, 
    setMisbehavePeer=std::set with 0 elements)
    at /home/mathxh/projects/FnFnCoreWallet/src/netchn.cpp:561
#11 0x000000000048965e in multiverse::CNetChannel::HandleEvent (this=0xb79ed0, 
    eventBlock=...) at /home/mathxh/projects/FnFnCoreWallet/src/netchn.cpp:427
#12 0x000000000049d814 in multiverse::network::CMvEventPeerData<32775, multiverse::network::CMvPeerEventListener, CBlock>::Handle (this=0x7fffec006390, 
    listener=...)
    at /home/mathxh/projects/FnFnCoreWallet/src/../network/mvpeerevent.h:45
#13 0x0000000000579efe in walleve::CWalleveEventProc::EventThreadFunc (
---Type <return> to continue, or q <return> to quit---
    this=0xb79ed0)
    at /home/mathxh/projects/FnFnCoreWallet/walleve/walleve/event/eventproc.cpp:45
#14 0x000000000057ba67 in boost::_mfi::mf0<void, walleve::CWalleveEventProc>::operator() (this=0xb79f40, p=0xb79ed0)
    at /usr/include/boost/bind/mem_fn_template.hpp:49
#15 0x000000000057b78a in boost::_bi::list1<boost::_bi::value<walleve::CWalleveEventProc*> >::operator()<boost::_mfi::mf0<void, walleve::CWalleveEventProc>, boost::_bi::list0> (this=0xb79f50, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:253
#16 0x000000000057b3cc in boost::_bi::bind_t<void, boost::_mfi::mf0<void, walleve::CWalleveEventProc>, boost::_bi::list1<boost::_bi::value<walleve::CWalleveEventProc*> > >::operator() (this=0xb79f40) at /usr/include/boost/bind/bind.hpp:893
#17 0x000000000057af6c in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<void, boost::_mfi::mf0<void, walleve::CWalleveEventProc>, boost::_bi::list1<boost::_bi::value<walleve::CWalleveEventProc*> > >, void>::invoke
    (function_obj_ptr=...)
    at /usr/include/boost/function/function_template.hpp:159
#18 0x0000000000587b51 in boost::function0<void>::operator() (this=0xb79f38)
    at /usr/include/boost/function/function_template.hpp:773
#19 0x0000000000583f14 in walleve::CWalleveDocker::ThreadRun (
    this=0xb3c208 <mvEntry+1608>, thr=...)
    at /home/mathxh/projects/FnFnCoreWallet/walleve/walleve/docker/docker.cpp:38---Type <return> to continue, or q <return> to quit---
3
#20 0x0000000000592068 in boost::_mfi::mf1<void, walleve::CWalleveDocker, walleve::CWalleveThread&>::operator() (this=0xbd12f8, p=0xb3c208 <mvEntry+1608>, 
    a1=...) at /usr/include/boost/bind/mem_fn_template.hpp:165
#21 0x0000000000591f4d in boost::_bi::list2<boost::_bi::value<walleve::CWalleveDocker*>, boost::reference_wrapper<walleve::CWalleveThread> >::operator()<boost::_mfi::mf1<void, walleve::CWalleveDocker, walleve::CWalleveThread&>, boost::_bi::list0> (this=0xbd1308, f=..., a=...) at /usr/include/boost/bind/bind.hpp:313
#22 0x0000000000591e5e in boost::_bi::bind_t<void, boost::_mfi::mf1<void, walleve::CWalleveDocker, walleve::CWalleveThread&>, boost::_bi::list2<boost::_bi::value<walleve::CWalleveDocker*>, boost::reference_wrapper<walleve::CWalleveThread> > >::operator() (this=0xbd12f8) at /usr/include/boost/bind/bind.hpp:893
#23 0x0000000000591dee in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf1<void, walleve::CWalleveDocker, walleve::CWalleveThread&>, boost::_bi::list2<boost::_bi::value<walleve::CWalleveDocker*>, boost::reference_wrapper<walleve::CWalleveThread> > > >::run (this=0xbd1140)
    at /usr/include/boost/thread/detail/thread.hpp:116
#24 0x0000000000569c95 in thread_proxy ()
#25 0x00007ffff75146ba in start_thread (arg=0x7ffff1d90700)
    at pthread_create.c:333
#26 0x00007ffff5ef441d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```

**Comment by AlexiaChen** [comment]
推块一段时间,GetHash的BufStream的流写入就crash了，这个不可能是多线程问题了，ss对象都在栈上，没暴露出去。
```cpp
   uint256 GetHash() const
    {
        walleve::CWalleveBufStream ss;
        ss << (*this);
        return multiverse::crypto::CryptoHash(ss.GetData(),ss.GetSize());
    }
```

**Comment by sunhantao** [comment]
Duplicate of #44. Fixed in e4560d6
